version: '3'
services:
  postgres-db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: myorg
      POSTGRES_USER: foo
      POSTGRES_PASSWORD: example123
    stop_grace_period: 75s

  activemq:
    image: symptoma/activemq:latest
    ports:
      - "61616:61616"
      - "8161:8161"
    stop_grace_period: 75s

  testapp:
    image: kamaraj/spring-boot-graceful-shutdown:1.0.0
    depends_on:
      - activemq
      - postgres-db
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - JAVA_OPTS=-XshowSettings:vm -XX:MetaspaceSize=64M -XX:MaxMetaspaceSize=128M -XX:+UseG1GC -XX:+ExitOnOutOfMemoryError -XX:+UseStringDeduplication -XX:G1PeriodicGCSystemLoadThreshold=0.5 -XX:G1PeriodicGCInterval=210000 -XX:-G1PeriodicGCInvokesConcurrent -Dspring.config.location=classpath:/application.yml -Dspring.datasource.url=jdbc:postgresql://postgres-db:5432/myorg -Dspring.activemq.broker-url=tcp://activemq:61616 -Dspring.jmx.enabled=false -Duser.timezone=UTC -Duser.country=US -Duser.language=en
      - TEST_ENABLED=true
    healthcheck:
      test: curl --fail http://localhost:8081/actuator/health || exit 1
      interval: 60s
      retries: 5
      timeout: 10s
    stop_grace_period: 70s
